#!/usr/bin/env node
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

const envPath = path.resolve(process.cwd(), ".env");
if (!fs.existsSync(envPath)) {
  console.error("Missing .env file. Please create one based on .env.example.");
  process.exit(1);
}

dotenv.config({ path: envPath });

const requiredKeys = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
];

const missingKeys = requiredKeys.filter((key) => !process.env[key]);
if (missingKeys.length) {
  console.error(
    `Missing required Firebase environment variables: ${missingKeys.join(", ")}`
  );
  process.exit(1);
}

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
};

const fileHeader = "// Auto-generated by scripts/generateFirebaseConfig.js\n";
const fileBody = `export const firebaseConfig = ${JSON.stringify(
  firebaseConfig,
  null,
  2
)};\n`;

fs.writeFileSync(
  path.resolve(process.cwd(), "firebase-config.js"),
  `${fileHeader}${fileBody}`,
  "utf-8"
);

console.log("firebase-config.js generated successfully.");
